name: aws-autorecycle

services:
  common:
    build:
      context: git@github.com:hmrc/infrastructure-pipeline-lambda-build.git#taskfile:containers/lambda
      additional_contexts:
        lambda_package: .
      args:
        PYTHON_VERSION: 3.11
      ssh: ["default"]

  lambda:
    extends:
      service: common
    build:
      target: release
      tags:
        - ${IMAGE_URI}
    command: monitor_autorecycle.main.lambda_handler

  test:
    extends:
      service: common
    build:
      target: test
    depends_on:
      - lambda
