version: "3"

env:
  IMAGE_URI: '{{.IMAGE_URI | default "aws-autorecycle:latest"}}'
  SKIP_TYPE_CHECKING: true

includes:
  infrastructure-pipeline-lambda-build:
    taskfile: git@github.com:hmrc/infrastructure-pipeline-lambda-build.git?ref=taskfile
    flatten: true
