# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3.53"

env:
  IMAGE_URI: '{{.IMAGE_URI | default "aws-autorecycle:latest"}}'
  SKIP_TYPE_CHECKING: true

includes:
  infrastructure-pipeline-lambda-build:
    taskfile: git@github.com:hmrc/infrastructure-pipeline-lambda-build.git?ref=taskfile
    flatten: true
